#--------- This file is automatically generated by LSST's sconsUtils ---------#
__version__ = 'unknown'
__repo_version__ = 'unknown'
__repo_version__ = 'unknown'
__fingerprint__ = 'b5514ec4d84a1e2f5d8183c22104991b0d5b4a5e *'
__dependency_versions__ = {
}
__all__ = ('__version__', '__repo_version__', '__repo_version__', '__fingerprint__', '__dependency_versions__')
