#!/bin/tcsh
python $PIPE_TASKS_DIR/bin/processCcd.py /raid/pgee/mylsst7/measMosaicData/input_renamed --configfile=processCcd0.py --clobber-config --id visit=100 raft=2,2 sensor=1,1 filter=i  --output mmout11
