#!/bin/tcsh
setenv visit $1
setenv config $2
setenv usage "Usage: processCcd1 visit configfile"

if (! -e "$2") then
    echo "The config file '$2' does not exist"
    echo $usage
    exit 1
endif
cat processCcd.py $config > temp.py
python $PIPE_TASKS_DIR/bin/processCcd.py /raid/pgee/mylsst7/measMosaicData/input_renamed --clobber-config --configfile=temp.py --id visit=$visit raft=2,2 sensor=1,1 filter=i  --output mmout1
