#!/bin/tcsh
setenv usage "Usage: processCcd0 visit [configfile]"
if ($1 == "") then
    echo "Visit must be specified"
    echo $usage
    exit 1
endif
setenv visit $1
cat processCcd.py > temp.py
if ($2 != "") then
    setenv config $2.py
    if (! -e $config) then
        echo "The config file '$config' does not exist"
        echo $usage
        exit 1
    endif
    cat $config >> temp.py
endif
python $PIPE_TASKS_DIR/bin/processCcd.py /raid/pgee/mylsst7/measMosaicData/input_renamed --clobber-config --configfile=temp.py --id visit=$visit raft=2,2 sensor=1,1 filter=i  --output mmout1
